### ISSUE TITLE
galois.is_irreducible(poly) seems to return some false negatives in large odd exponent GFs

### ISSUE THREAD

**Issue by geostergiop** [mhostetter/galois#360]
Hi Matt, hope all is well.

Even though it works fine for other groups (e.g. even groups likes GF(2^256) work well), still I 've been getting the following false negative result when using the galois.is_irreducible(poly) over odd groups tο produce irreducible polynomials over GF(2^233). 

For example, we know from previous publications and research that x^233+x^74+1 is irreducible over GF(2) for creating the quotient ring of GF(2^233) but the following code returns Null for every polynomial (including the aforementioned one):
```
def loop_init_trinomial():
    #initial detection loop
    for k in range(1, 233):
        poly = galois.Poly.Degrees([233, k, 0])
        if galois.is_irreducible(poly):
            print("Found one: ", k, poly, poly.string)
```
Care to share some thoughts?

**Comment by mhostetter** [comment]
@geostergiop it turned out not to be an algorithm issue. Instead, the issue was a `np.int64` invaded some integer arithmetic, which coerced all other `int`s to `np.int64`. In irreducibility checks, you have to do `q**m`, and if either is `np.int64` not `int`, the calculation can overflow. The downstream calculations are then incorrect.

See #361 for more details. It will be merged into `master` in ~20 mins.

**Comment by mhostetter** [comment]
I can't be certain, to be honest. Did you discover this bug after updating versions? I believe this bug was introduced recently.

**Comment by geostergiop** [comment]
Yep sorry, bad reference!
